name: depremdudugu
description: Whistle (S.O.S)

publish_to: "none"

version: 3.3.0+13

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_localizations:
    sdk: flutter
  number_inc_dec: ^0.8.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  simple_speed_dial: ^0.1.7
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/icons/
    - assets/img/
    - assets/lang/en.json
    - assets/lang/tr.json
